[tools]
gradle = "latest"
java = "17"
nim = { version = "latest", postinstall = "nimble install -y --silent nph nimlangserver" }
watchexec = "latest"

[hooks]
postinstall = "nimble install -yl --silent --depsOnly"

[tasks.clear]
run = """
nimble clean --silent
rm -rf build/ android/.gradle android/app/.cxx android/app/build
cd android && ./gradlew clean -q || true
"""

[tasks.nim_android]
run = """
nim c --os:android manim.nim
NIM_LIB_DIR=$(nim dump 2>&1 | tail -n 1)
cp "$NIM_LIB_DIR/nimbase.h" build/android_cache/
"""
depends = ["clear", "web_build"]

[tasks.nim_build]
run = "nimble build --silent"
depends = ["clear"]

[tasks.macos_bundle]
usage = """
flag "-o --open" help="Open the app after bundling"
"""
run = """
mkdir -p build/Manim.app/Contents/MacOS
mv build/manim build/Manim.app/Contents/MacOS/manim
cp -R macos/public/ build/Manim.app/
if [ "${usage_open:-false}" = "true" ]; then
  mise open
fi
"""
depends = ["nim_build"]

[tasks.bundle_all]
depends = ["web_build", "macos_bundle"]

[tasks.dev]
usage = """
flag "-w --watch" help="Watch for changes"
"""
run = """# running nim r -d:debug manim.nim
if [ "${usage_watch:-false}" = "true" ]; then
  watchexec -c=reset -w manim.nim -qe nim 'nim r -d:debug manim.nim'
else
  nim r -d:debug manim.nim
fi
"""

[tasks.run]
run = "clear;build/manim"
depends = ["nim_build"]

[tasks.open]
run = """
pkill -x manim || true
while pgrep -x manim > /dev/null; do
  sleep 0.2
done
sleep 0.2
open build/Manim.app
"""

[tasks.android_emulator_create]
run = """
sdkmanager "system-images;android-35;google_apis;arm64-v8a"
avdmanager create avd -n Pixel_API_35 -k "system-images;android-35;google_apis;arm64-v8a" --device "pixel"
"""

[tasks.android_run]
run = """
nohup emulator -avd Pixel_API_35 -qemu -append "hw.keyboard=yes hw.keyboard.lid=no" > /dev/null 2>&1 &
"""

[tasks.android_logs]
run = "(adb logcat | grep -i 'Manim')"

[tasks.android_install]
run = """
cd android
./gradlew installDebug -q
adb shell am start -n dev.guima.manim/.MainActivity
"""
depends = ["nim_android"]

[tasks.android_build]
run = "cd android && ./gradlew assembleDebug"
depends = ["nim_android"]

[tasks.web_dev]
run = "dx -A astro dev"

[tasks.web_build]
run = "dx -A astro build --silent"

[tasks.astro]
run = "dx -A astro"
