{.used.}
import std/[macros, json, jsonutils, tables, strutils, strformat]
import ../lib/log

type RpcHandler* = proc(args: JsonNode): JsonNode

var rpcRegistry* = initTable[string, RpcHandler]()

var tsMethods {.compileTime.}: seq[string]

proc nimTypeToTs(nimType: string): string {.compileTime.} =
  ## Helper to map Nim types to TS types
  case nimType
  of "string": "string"
  of "int", "float", "int32", "int64", "uint", "uint32": "number"
  of "bool": "boolean"
  of "JsonNode": "any"
  of "void", "": "void"
  else: "any"
    # Fallback for complex objects for now

macro expose*(body: untyped): untyped =
  ## Registers `proc` or `func` for RPC calls, wrapping it with JSON handling logic.
  expectKind(body, {nnkProcDef, nnkFuncDef})

  let rawName = body.name
  let procIdent =
    if rawName.kind == nnkPostfix:
      rawName[1]
    else:
      rawName
  let procNameStr = newLit($procIdent)
  let procName = body.name
  let params = body.params
  let returnType = params[0]
  let requiresArgs = params.len > 1
  let isVoid = returnType.kind == nnkEmpty or $returnType == "void"

  var tsArgs = newSeq[string]()
  var jsPayloadDict = newSeq[string]()

  for i in 1 ..< params.len:
    let identDefs = params[i]
    let paramTypeNode = identDefs[^2]
    let tsType = nimTypeToTs($paramTypeNode)

    for j in 0 .. identDefs.len - 3:
      let paramName = $identDefs[j]
      tsArgs.add(fmt"{paramName}: {tsType}")
      jsPayloadDict.add(fmt"{paramName}")

  let tsRetType =
    if isVoid:
      "void"
    else:
      nimTypeToTs($returnType)
  let joinedTsArgs = tsArgs.join(", ")
  let joinedPayload =
    if jsPayloadDict.len > 0:
      jsPayloadDict.join(", ")
    else:
      ""

  tsMethods.add(
    fmt"""
      {procIdent}({joinedTsArgs}) {{
        return rpcCall<{tsRetType}>({{ cmd: '{procIdent}', {joinedPayload} }})
      }},""".dedent
  )

  let argsIdent = ident("args")
  var extractStmts = newStmtList()
  var callArgs = newSeq[NimNode]()

  # JSON extraction statements for each parameter
  for i in 1 ..< params.len:
    let identDefs = params[i]
    let paramType = identDefs[^2]

    for j in 0 .. identDefs.len - 3:
      let paramName = identDefs[j]
      let paramNameStr = newLit($paramName)
      extractStmts.add quote do:
        let `paramName` = jsonTo(`argsIdent`[`paramNameStr`], `paramType`)
      callArgs.add paramName

  let callExpr = newCall(procName, callArgs)

  let executeAndReturn =
    if isVoid: # void vs data
      quote:
        `callExpr`
        newJNull()
    else:
      quote:
        toJson(`callExpr`)

  let argsCheck =
    if requiresArgs:
      quote:
        if `argsIdent` == nil or `argsIdent`.kind != JObject:
          return %*{
            "error": true,
            "message":
              "Expected 'data' to be a JSON object containing the function arguments.",
          }
    else:
      newStmtList()

  result = quote:
    `body` # Original proc
    rpcRegistry[`procNameStr`] = proc(`argsIdent`: JsonNode): JsonNode =
      try:
        `argsCheck`
        `extractStmts`
        return `executeAndReturn`
      except CatchableError as e:
        return %*{"error": true, "message": e.msg}

macro generateTsBindings*(outputPath: static[string]): untyped =
  ## Generates TypeScript bindings for RPC methods registered with `expose`.
  let fileContent = fmt"""
    // AUTO-GENERATED BY MANIM RPC
    // Do not edit this file directly.
    declare global {{
      interface Window {{
        __ManimNative: {{
          postMessage<T> (payload: string): Promise<T>
        }}
        __ManimSSE: EventSource
        webkit?: {{
          messageHandlers: {{
            manim: {{
              postMessage<T> (payload: string): Promise<T>
            }}
          }}
        }}
      }}
    }}

    const RPC_ENDPOINT = 'https://guimabook.local:4568/rpc'

    const serialize = (o: unknown) => JSON.stringify(o)
    async function rpcCall<T>(payload: unknown): Promise<T> {{
      const p = serialize(payload)
      if (globalThis.window.__ManimNative) {{
        return await globalThis.window.__ManimNative.postMessage<T>(p)
      }} else if (globalThis.window.webkit?.messageHandlers?.manim) {{
        return await globalThis.window.webkit.messageHandlers.manim.postMessage(p) as T
      }} else {{
        const res = await fetch(RPC_ENDPOINT, {{ method: 'POST', body: p }})
        return (await res.json()) as T
      }}
    }}

    export function listen<T extends unknown>(eventName: string, callback: (payload: T) => void) {{
      const isNative = globalThis.window.__ManimNative || globalThis.window.webkit?.messageHandlers?.manim
      if (!isNative) {{
        if (!globalThis.window.__ManimSSE) {{
          globalThis.window.__ManimSSE = new EventSource(RPC_ENDPOINT)
        }}

        const evtSource = globalThis.window.__ManimSSE as EventSource
        evtSource.addEventListener(eventName, (e: MessageEvent) => callback(JSON.parse(e.data) as T))
        return
      }}

      const manimEvent = `manim:${{eventName}}`
      globalThis.addEventListener(
        manimEvent,
        (e: Event) => callback((e as CustomEvent<T>).detail),
      )
    }}

    export const rpc = {{
{tsMethods.join("\n").indent(6)}
    }}
    export default rpc
  """.dedent()

  writeFile(outputPath, fileContent)
  return newStmtList()

proc routeMessage*(payloadStr: string): string =
  ## Routes an incoming JSON RPC message to the appropriate RPC handler
  try:
    let payload = parseJson(payloadStr)

    if payload.kind != JObject or not payload.hasKey("cmd"):
      return $ %*{
        "event": "error",
        "data": "Invalid payload format. Expected JSON object with a 'cmd' key.",
      }

    let command = payload["cmd"].getStr()
    payload.delete("cmd")
    let args = payload

    log "received: " & command & ", " & $(%*args)

    if rpcRegistry.hasKey(command):
      let dataNode = rpcRegistry[command](args)
      if dataNode.kind == JObject and dataNode.hasKey("error"):
        return $ %*{"event": "error", "data": dataNode["message"]}
      else:
        return $ %*dataNode
    else:
      return $ %*{"event": "error", "data": fmt"Command '{command}' not found"}
  except Exception as e:
    return $ %*{"event": "error", "data": fmt"RPC parsing error: {e.msg}"}
