{.used.}
import std/[macros, json, jsonutils, tables, strutils, strformat]
import ../lib/log

type RpcHandler* = proc(args: JsonNode): JsonNode

var rpcRegistry* = initTable[string, RpcHandler]()

var tsMethods {.compileTime.}: seq[string]

proc nimTypeToTs(nimType: string): string {.compileTime.} =
  ## Helper to map Nim types to TS types
  case nimType
  of "string": "string"
  of "int", "float", "int32", "int64", "uint", "uint32": "number"
  of "bool": "boolean"
  of "JsonNode": "any"
  of "void", "": "void"
  else: "any" ## Fallback for complex objects for now

macro expose*(body: untyped): untyped =
  ## Registers `proc` or `func` for RPC calls, wrapping it with JSON handling logic.
  expectKind(body, {nnkProcDef, nnkFuncDef})

  let rawName = body.name
  let procIdent =
    if rawName.kind == nnkPostfix:
      rawName[1]
    else:
      rawName
  let procNameStr = newLit($procIdent)
  let procName = body.name
  let params = body.params
  let returnType = params[0]
  let requiresArgs = params.len > 1

  var tsArgs = newSeq[string]()
  var jsPayloadDict = newSeq[string]()

  for i in 1 ..< params.len:
    let identDefs = params[i]
    let paramTypeNode = identDefs[^2]
    let tsType = nimTypeToTs($paramTypeNode)

    for j in 0 .. identDefs.len - 3:
      let paramName = $identDefs[j]
      tsArgs.add(fmt"{paramName}: {tsType}")
      jsPayloadDict.add(fmt"{paramName}")

  let tsRetType = if returnType.kind == nnkEmpty: "void" else: nimTypeToTs($returnType)
  let joinedTsArgs = tsArgs.join(", ")
  let joinedPayload = if jsPayloadDict.len > 0: jsPayloadDict.join(", ") else: ""

  let tsMethod = fmt"""
    {procIdent}({joinedTsArgs}) {{
      return rpcCall<{tsRetType}>(JSON.stringify({{ rpc_event: '{procIdent}', {joinedPayload} }}))
    }},""".dedent(1)

  tsMethods.add(tsMethod)

  let argsIdent = ident("args")
  var extractStmts = newStmtList()
  var callArgs = newSeq[NimNode]()

  # JSON extraction statements for each parameter
  for i in 1 ..< params.len:
    let identDefs = params[i]
    let paramType = identDefs[^2]

    for j in 0 .. identDefs.len - 3:
      let paramName = identDefs[j]
      let paramNameStr = newLit($paramName)
      extractStmts.add quote do:
        let `paramName` = jsonTo(`argsIdent`[`paramNameStr`], `paramType`)
      callArgs.add paramName

  let callExpr = newCall(procName, callArgs)

  let executeAndReturn =
    if returnType.kind == nnkEmpty: # void vs data
      quote:
        `callExpr`
        newJNull()
    else:
      quote:
        toJson(`callExpr`)

  let argsCheck =
    if requiresArgs:
      quote:
        if `argsIdent` == nil or `argsIdent`.kind != JObject:
          return %*{
            "error": true,
            "message":
              "Expected 'data' to be a JSON object containing the function arguments.",
          }
    else:
      newStmtList()

  result = quote:
    `body` # Original proc
    rpcRegistry[`procNameStr`] = proc(`argsIdent`: JsonNode): JsonNode =
      try:
        `argsCheck`
        `extractStmts`
        return `executeAndReturn`
      except CatchableError as e:
        return %*{"error": true, "message": e.msg}

macro generateTsBindings*(outputPath: static[string]): untyped =
  ## Generates TypeScript bindings for RPC methods registered with `expose`.
  let joinedMethods = tsMethods.join("\n")
  let fileContent = fmt"""
// AUTO-GENERATED BY MANIM RPC
// Do not edit this file directly.
declare global {{
  interface Window {{
  __ManimNative: {{
      postMessage<T> (payload: string): Promise<T>;
    }}
  }}
}}

const RPC_ENDPOINT = 'https://rpc.guima.localhost/rpc';

async function rpcCall<T>(payload: string): Promise<T> {{
  if (globalThis.window.__ManimNative) {{
    return await globalThis.window.__ManimNative.postMessage<T>(payload);
  }} else {{
    const res = await fetch(RPC_ENDPOINT, {{ method: 'POST', body: payload }})
    const json = await res.json();
    return json as T;
  }}
}}

export function listen(eventName: string, callback: (payload: any) => void) {{
  if (!globalThis.window.__ManimNative) {{
    if (!(globalThis.window as any).__ManimSSE) {{
      (globalThis.window as any).__ManimSSE = new EventSource(RPC_ENDPOINT);
    }}

    const evtSource = (globalThis.window as any).__ManimSSE as EventSource;
    evtSource.addEventListener(eventName, (e: MessageEvent) => {{
      callback(JSON.parse(e.data));
    }});
    return;
  }}

  const manimEvent = `manim:${{eventName}}`;
  window.addEventListener(manimEvent, ((e: CustomEvent) => {{
    callback(e.detail);
  }}) as EventListener);
}}

export const rpc = {{
{joinedMethods}
}};
export default rpc;
""".dedent()

  writeFile(outputPath, fileContent)
  return newStmtList()


proc routeMessage*(payloadStr: string): string =
  ## Routes an incoming JSON RPC message to the appropriate RPC handler
  try:
    let payload = parseJson(payloadStr)

    if payload.kind != JObject or not payload.hasKey("rpc_event"):
      return $ %*{"rpc_event": "error", "data": "Invalid payload format. Expected JSON object with an 'rpc_event' key."}

    let eventName = payload["rpc_event"].getStr()
    payload.delete("rpc_event")
    let args = payload

    log "received: " & eventName & ", " & $(%*args)

    if rpcRegistry.hasKey(eventName):
      let dataNode = rpcRegistry[eventName](args)
      if dataNode.kind == JObject and dataNode.hasKey("error"):
        return $ %*{"rpc_event": "error", "data": dataNode["message"]}
      else:
        return $ %*dataNode
    else:
      return $ %*{"rpc_event": "error", "data": fmt"Method '{eventName}' not found"}
  except Exception as e:
    return $ %*{"rpc_event": "error", "data": fmt"RPC parsing error: {e.msg}"}
