// AUTO-GENERATED BY NIMOY
// Do not edit this file directly.
declare global {
  interface Window {
    __Native: {
      postMessage<T>(payload: string): Promise<T>
    }
    __SSE: EventSource
    webkit?: {
      messageHandlers: {
        nimoy: {
          postMessage<T>(payload: string): Promise<T>
        }
      }
    }
  }
}

const RPC_ENDPOINT = 'https://guimabook.local:4568/rpc'

const serialize = (o: unknown) => JSON.stringify(o)
async function _rpcCall<T>(payload: unknown): Promise<T> {
  const body = serialize(payload)
  if (globalThis.window.__Native) {
    return await globalThis.window.__Native.postMessage<T>(body)
  } else if (globalThis.window.webkit?.messageHandlers?.nimoy) {
    return await globalThis.window.webkit.messageHandlers.nimoy.postMessage<T>(body)
  } else {
    const res = await fetch(RPC_ENDPOINT, { method: 'POST', body })
    return (await res.json()) as T
  }
}

export function listen<T extends unknown>(eventName: string, callback: (payload: T) => void) {
  const isNative = globalThis.window.__Native || globalThis.window.webkit?.messageHandlers?.nimoy
  if (!isNative) {
    if (!globalThis.window.__SSE) {
      globalThis.window.__SSE = new EventSource(RPC_ENDPOINT)
    }

    const source = globalThis.window.__SSE as EventSource
    source.addEventListener(eventName, (e: MessageEvent) => callback(JSON.parse(e.data) as T))
    return
  }

  globalThis.addEventListener(
    `_RPC:${eventName}`,
    (e: Event) => callback((e as CustomEvent<T>).detail),
  )
}

listen('_RPC:ping', () => {
  _rpcCall({ event: 'pong' })
})

export const rpc = {
  // RPC methods
}
export default rpc
