[tools]
nim = { version = "latest", postinstall = "nimble install -y --silent nph nimlangserver" }
usage = "latest"
watchexec = "latest"

[hooks]
postinstall = "nimble install -yl --silent --depsOnly"

[tasks.clear]
run = "nimble clean --silent"

[tasks.build]
run = "nimble build --silent"
depends = ["clear"]

[tasks.dev]
run = """
./one_br.nim
"""

[tasks.run]
run = "clear;dist/one_br"
depends = ["build"]

[tasks.gen]
run = "./gen_input.nim"
