// AUTO-GENERATED BY NIMOY
// Do not edit this file directly.

declare global {
  interface Window {
    __Nimoy: {
      postMessage<T>(payload: string): Promise<T>
    }
    __NimoySSE: EventSource
    webkit?: {
      messageHandlers?: {
        __Nimoy?: {
          postMessage<T>(payload: string): Promise<T>
        }
      }
    }
  }
}

const RPC_ENDPOINT = '/rpc'

const serialize = (o: unknown) => JSON.stringify(o)
async function _rpcCall<T>(payload: unknown): Promise<T> {
  const body = serialize(payload)
  if (globalThis.window.__Nimoy) {
    return await globalThis.window.__Nimoy.postMessage<T>(body)
  } else if (globalThis.window.webkit?.messageHandlers?.__Nimoy) {
    return await globalThis.window.webkit.messageHandlers.__Nimoy.postMessage<T>(body)
  } else {
    const res = await fetch(RPC_ENDPOINT, { method: 'POST', body })
    return (await res.json()) as T
  }
}

export function listen<T extends unknown>(eventName: string, callback: (payload: T) => void) {
  const isNative = globalThis.window.__Nimoy || globalThis.window.webkit?.messageHandlers?.__Nimoy
  if (!isNative) {
    if (!globalThis.window.__NimoySSE) {
      globalThis.window.__NimoySSE = new EventSource(RPC_ENDPOINT)
    }

    const source = globalThis.window.__NimoySSE as EventSource
    source.addEventListener(eventName, (e: MessageEvent) => callback(JSON.parse(e.data) as T))
    return
  }

  globalThis.addEventListener(
    `_NIMOY:${eventName}`,
    (e: Event) => callback((e as CustomEvent<T>).detail),
  )
}

export const rpc = {
  something(someInput: string) {
    return _rpcCall<any>({ cmd: 'something', someInput })
  },
}
export default rpc
